
FROM openjdk:22-oracle

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY ExpenseTrackerApplication.jar /app/ExpenseTrackerApplication.jar

# Specify the command to run the JAR file
CMD ["java", "-jar", "ExpenseTrackerApplication.jar"]
